import {expect,test} from '@playwright/test';
import {copyFile,mkdir,readFile} from 'node:fs/promises';
import JSZip from 'jszip';
import {downloadDevicePreset,expectMultisampleLoaded,gotoWorkspace,openWorkspace,projectAction} from './workspace-actions';

declare global {interface Window {__autoSampleMidi:number[][];__autoSampleMidiRequests:number}}

test('production Chromium captures an exact synthetic MIDI range through only explicit fake audio and MIDI devices',async({page,context,baseURL})=>{
  test.setTimeout(90_000);
  test.skip(!process.env.PLAYWRIGHT_FAKE_AUDIO_FILE,'An explicit fake audio file is required');if(!baseURL)throw new Error('Synthetic capture requires its configured local origin');
  await page.addInitScript(()=>{
    const messages:number[][]=[];class FakeOutput extends EventTarget {id='synthetic-midi-output';name='Synthetic MIDI output';manufacturer='OP Patchstudio test';type='output';state='connected';connection='open';onstatechange=null;send(data:Uint8Array|number[]){messages.push(Array.from(data));}clear(){}async open(){this.connection='open';return this}async close(){this.connection='closed';return this}}
    const access=new EventTarget() as EventTarget&{inputs:Map<string,never>;outputs:Map<string,FakeOutput>;sysexEnabled:boolean;onstatechange:null};access.inputs=new Map();const output=new FakeOutput();access.outputs=new Map([[output.id,output]]);access.sysexEnabled=false;access.onstatechange=null;
    Object.defineProperty(window,'__autoSampleMidiRequests',{value:0,writable:true});Object.defineProperty(navigator,'requestMIDIAccess',{configurable:true,value:async()=>{window.__autoSampleMidiRequests+=1;return access;}});Object.defineProperty(window,'__autoSampleMidi',{value:messages});
  });
  await context.grantPermissions(['microphone'],{origin:new URL(baseURL).origin});await gotoWorkspace(page,'multisample');
  const devices=await page.evaluate(async()=>navigator.mediaDevices.enumerateDevices()),audioInputs=devices.filter(device=>device.kind==='audioinput');expect(audioInputs.length).toBeGreaterThan(0);expect(audioInputs.every(device=>device.label.startsWith('Fake '))).toBe(true);
  await page.getByRole('button',{name:'Record takes',exact:true}).first().click();const dialog=page.getByRole('dialog',{name:'Record takes'});await expect(dialog).toBeVisible();await dialog.getByLabel('Input device').selectOption({label:audioInputs.find(device=>device.label==='Fake Audio Input 1')?.label??audioInputs[0].label});
  expect(await page.evaluate(()=>window.__autoSampleMidiRequests)).toBe(0);await page.screenshot({path:'docs/verification/auto-sampling-desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/verification/auto-sampling-narrow.png'});await page.setViewportSize({width:1280,height:720});await dialog.getByRole('button',{name:'Enable MIDI'}).click();expect(await page.evaluate(()=>window.__autoSampleMidiRequests)).toBe(1);await dialog.getByLabel('MIDI output').selectOption('synthetic-midi-output');await dialog.getByRole('button',{name:'Test one note'}).click();await expect.poll(()=>page.evaluate(()=>window.__autoSampleMidi.length)).toBe(1);await dialog.getByRole('button',{name:'Stop automatic capture'}).click();await expect.poll(()=>page.evaluate(()=>window.__autoSampleMidi.length)).toBe(2);await expect(dialog.getByRole('status')).toContainText('stopped');await dialog.getByRole('button',{name:'Close'}).click();await page.getByRole('button',{name:'Record takes',exact:true}).first().click();await expect(dialog).toBeVisible();await dialog.getByLabel('Input device').selectOption({label:audioInputs.find(device=>device.label==='Fake Audio Input 1')?.label??audioInputs[0].label});await expect(dialog.getByRole('button',{name:'MIDI enabled'})).toBeDisabled();await expect(dialog.getByLabel('MIDI output')).toHaveValue('synthetic-midi-output');await page.evaluate(()=>{window.__autoSampleMidi.length=0;});for(const [label,value] of [['Start note','60'],['End note','66'],['Note step','6'],['Hold duration','0.1'],['Release tail','0.1'],['Between-note settling','0']] as const)await dialog.getByLabel(label).fill(value);
  await dialog.getByRole('button',{name:'Start automatic capture'}).click();await expect(dialog.locator('input[aria-label^="Root note for take"]')).toHaveCount(2,{timeout:15_000});expect(await dialog.locator('input[aria-label^="Root note for take"]').evaluateAll(nodes=>nodes.map(node=>(node as HTMLInputElement).value))).toEqual(['60','66']);await expectMultisampleLoaded(page,0);
  expect(await page.evaluate(()=>window.__autoSampleMidi)).toEqual([[0x90,60,100],[0x80,60,0],[0x90,66,100],[0x80,66,0]]);await dialog.getByRole('button',{name:'Add selected takes'}).click();await expectMultisampleLoaded(page,2);await dialog.getByRole('button',{name:'Close'}).click();await page.getByRole('textbox',{name:'Instrument name',exact:true}).fill('Synthetic automatic multisample');
  const evidence='docs/verification/auto-sampling-final-evidence';await mkdir(evidence,{recursive:true});const projectEvent=page.waitForEvent('download');await projectAction(page,'Download project');const project=await projectEvent,projectPath=await project.path();expect(await project.failure()).toBeNull();if(!projectPath)throw new Error('Automatic multisample project produced no file');await copyFile(projectPath,`${evidence}/synthetic-two-note-capture.opstudio`);
  const download=await downloadDevicePreset(page),path=await download.path();expect(await download.failure()).toBeNull();if(!path)throw new Error('Automatic multisample export produced no file');await copyFile(path,`${evidence}/synthetic-two-note-opxy.zip`);const zip=await JSZip.loadAsync(await readFile(path)),patchFile=zip.file('patch.json');expect(patchFile).not.toBeNull();const patch=JSON.parse(await patchFile!.async('string')) as {regions:Array<{sample:string;framecount:number}>};expect(patch.regions).toHaveLength(2);for(const region of patch.regions){expect(region.framecount).toBeGreaterThan(0);expect(zip.file(region.sample)).not.toBeNull();}
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload({waitUntil:'domcontentloaded'});await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});const restore=page.getByRole('dialog',{name:'restore session'});await expect(restore).toContainText('2 multisample files');await restore.getByRole('button',{name:'restore',exact:true}).click();await expect(restore).toBeHidden();await openWorkspace(page,'multisample');await expectMultisampleLoaded(page,2);await page.getByRole('button',{name:'Record takes',exact:true}).first().click();await expect(dialog).toBeVisible();await dialog.getByLabel('Input device').selectOption({label:audioInputs.find(device=>device.label==='Fake Audio Input 1')?.label??audioInputs[0].label});await dialog.getByRole('button',{name:'Enable MIDI'}).click();await dialog.getByLabel('MIDI output').selectOption('synthetic-midi-output');await dialog.getByLabel('Start note').fill('48');for(const label of ['Hold duration','Release tail'])await dialog.getByLabel(label).fill('0.1');await dialog.getByRole('button',{name:'Test one note'}).click();await expect(dialog.locator('input[aria-label^="Root note for take"]')).toHaveCount(1,{timeout:15_000});expect(await page.evaluate(()=>window.__autoSampleMidi)).toEqual([[0x90,48,100],[0x80,48,0]]);await context.setOffline(false);
});
