import {test,expect} from './control-audit-test';
import {gotoWorkspace,openAdvanced} from './workspace-actions';
import {applyAudioImport} from './import-helpers';
import JSZip from 'jszip';
import {readFile,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
function tone(name='entry.wav',phase=0){const n=4800,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(48000,24);b.writeUInt32LE(96000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(12000*Math.sin(i/(20+phase))),44+i*2);return{name,mimeType:'audio/wav',buffer:b};}
for(const workspace of ['drum','multisample'] as const)test(`${workspace} Browse folder reviews files and Cancel keeps the empty instrument`,async({page})=>{
 const folder=await mkdtemp(path.join(tmpdir(),'opstudio-folder-test-'));try{
  for(const [index,name] of ['first-C4.wav','second-D4.wav'].entries())await writeFile(path.join(folder,name),tone(name,index).buffer);
  await gotoWorkspace(page,workspace);const choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'browse folder',exact:true}).click();await(await choosing).setFiles(folder);
  const review=page.getByRole('dialog',{name:'Import audio',exact:true});for(const name of ['first-C4.wav','second-D4.wav'])await expect(review.getByText(name,{exact:true})).toBeVisible();await review.getByRole('button',{name:'Cancel import',exact:true}).click();await expect(review).toBeHidden();await expect(page.getByRole('region',{name:workspace==='drum'?'Drum pad instrument, 0 of 24 loaded':'Multisample instrument, 0 of 24 loaded',exact:true})).toBeVisible();
 }finally{await rm(folder,{recursive:true,force:true});}
});
test('multisample patch settings chooser imports atomically and supports Undo',async({page})=>{
 await gotoWorkspace(page,'multisample');const settings=await openAdvanced(page,/Preset and performance settings/);await settings.getByRole('heading',{name:'advanced',exact:true}).click();const slider=settings.locator('#multisample-transpose');const before=await slider.getAttribute('aria-valuenow');const choosing=page.waitForEvent('filechooser');await settings.getByRole('button',{name:/import patch\.json/}).click();await(await choosing).setFiles({name:'patch.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({type:'multisampler',engine:{playmode:'mono',transpose:9}}))});await expect(page.getByText('successfully imported multisample preset settings',{exact:true})).toBeVisible();await expect(slider).toHaveAttribute('aria-valuenow','9');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(slider).toHaveAttribute('aria-valuenow',before!);
});
test('drum import rejects malformed OP-1 files, auditions unassigned audio, and opens setup help',async({page})=>{
 await page.addInitScript(()=>{const start=AudioBufferSourceNode.prototype.start;Object.defineProperty(window,'__fileEntryPlays',{value:0,writable:true});AudioBufferSourceNode.prototype.start=function(...args:Parameters<AudioBufferSourceNode['start']>){Reflect.set(window,'__fileEntryPlays',Reflect.get(window,'__fileEntryPlays')+1);return start.apply(this,args);};});
 await gotoWorkspace(page,'drum');let choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'import OP-1 preset',exact:true}).click();await(await choosing).setFiles({name:'invalid.aiff',mimeType:'audio/aiff',buffer:Buffer.from('invalid')});await expect(page.getByText(/does not appear to be a valid OP-1 drum preset/)).toBeVisible();
 choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add sounds',exact:true}).click();await(await choosing).setFiles([tone(),tone('spare.wav',1)]);const review=page.getByRole('dialog',{name:'Import audio',exact:true});await review.getByLabel('Destination for entry.wav',{exact:true}).selectOption('unassigned');await applyAudioImport(page);const tray=page.getByRole('region',{name:'Unassigned sounds',exact:true});await expect(tray.getByRole('button',{name:'entry.wav',exact:true})).toBeVisible();await tray.getByRole('button',{name:'Play',exact:true}).first().click();await expect.poll(()=>page.evaluate(()=>Reflect.get(window,'__fileEntryPlays'))).toBeGreaterThan(0);
 const guide=page.locator('details[aria-label="Kit setup guide"]');await guide.locator('summary').click();await guide.getByRole('button',{name:'Setup help',exact:true}).click();await expect(page.getByRole('dialog',{name:'Help',exact:true})).toBeVisible();
});
test('mobile empty drum table browse loads the chosen pad',async({page})=>{
 await page.setViewportSize({width:390,height:1000});await gotoWorkspace(page,'drum');await page.getByRole('button',{name:'Table',exact:true}).click();const choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'tap to browse for audio file',exact:true}).first().click();await(await choosing).setFiles(tone());await expect(page.getByRole('region',{name:'Drum pad instrument, 1 of 24 loaded',exact:true})).toBeVisible();await expect(page.getByText('entry.wav',{exact:true}).first()).toBeVisible();
});

test('multisample import inclusion and root edits commit together and Undo',async({page})=>{
 await gotoWorkspace(page,'multisample');const choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add samples',exact:true}).click();await(await choosing).setFiles([tone('chosen.wav'),tone('excluded.wav',2)]);
 const review=page.getByRole('dialog',{name:'Import audio',exact:true});await review.getByLabel('Root note for chosen.wav',{exact:true}).fill('65');await review.getByLabel('Include chosen.wav',{exact:true}).check();await review.getByLabel('Include excluded.wav',{exact:true}).uncheck();await review.getByRole('button',{name:'Apply import',exact:true}).click();await expect(review.getByLabel('Include chosen.wav',{exact:true})).toHaveCount(0);await expect(review.getByLabel('Include excluded.wav',{exact:true})).toBeVisible();await review.getByRole('button',{name:'Cancel import',exact:true}).click();
 await expect(page.getByRole('region',{name:'Multisample instrument, 1 of 24 loaded',exact:true})).toBeVisible();await page.getByRole('button',{name:'Table',exact:true}).click();await expect(page.getByPlaceholder('C4 or 60').first()).toHaveValue('F3');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('region',{name:'Multisample instrument, 0 of 24 loaded',exact:true})).toBeVisible();
});

test('export preflight edits name and includes unassigned sound only when requested',async({page,context})=>{
 await context.route(/^https:\/\//,route=>route.fulfill({status:200,contentType:'text/html',body:'Isolated guide'}));
 await gotoWorkspace(page,'drum');const choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add sounds',exact:true}).click();await(await choosing).setFiles([tone('kick.wav'),tone('spare.wav',2)]);
 const review=page.getByRole('dialog',{name:'Import audio',exact:true});await review.getByLabel('Destination for kick.wav',{exact:true}).selectOption('pad:0');await review.getByLabel('Destination for spare.wav',{exact:true}).selectOption('unassigned');await applyAudioImport(page);
 await page.getByRole('button',{name:'Export OP-XY',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Export OP-XY preset',exact:true});await dialog.getByLabel('Instrument name',{exact:true}).fill('Audited export');await dialog.getByText('File naming and format',{exact:true}).click();await expect(dialog.getByRole('combobox',{name:'Audio format',exact:true})).toBeVisible();
 const option=dialog.getByRole('checkbox',{name:/Include 1 unassigned sample/});await expect(option).not.toBeChecked();
 for(const include of [false,true]){
  await option.setChecked(include);const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download preset',exact:true}).click();const download=await pending;expect(await download.failure()).toBeNull();const zip=await JSZip.loadAsync(await readFile((await download.path())!));const patch=JSON.parse(await zip.file('patch.json')!.async('string'));expect(patch.regions).toHaveLength(1);expect(Object.keys(zip.files).filter(name=>/\.wav$/i.test(name))).toHaveLength(include?2:1);for(const region of patch.regions)expect(zip.file(region.sample)).not.toBeNull();
 }
 const link=dialog.getByRole('link',{name:'Open the current OP-XY transfer guide'}),href=await link.getAttribute('href');const opening=page.waitForEvent('popup');await link.click();const popup=await opening;await expect(popup).toHaveURL(href!);await popup.close();await dialog.press('Escape');await expect(dialog).toBeHidden();await expect(page.getByRole('textbox',{name:'Instrument name',exact:true})).toHaveValue('Audited export');
});

test('multisample zone selection and note naming do not change roots',async({page})=>{
 await gotoWorkspace(page,'multisample');const choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add samples',exact:true}).click();await(await choosing).setFiles([tone('first-C4.wav'),tone('second-D4.wav',2)]);await applyAudioImport(page);
 const editor=page.getByRole('region',{name:'Focused multisample editor'});await editor.getByRole('combobox',{name:'Selected multisample zone'}).selectOption('1');await expect(editor.getByRole('heading',{level:3})).toHaveText('first-C4.wav');const root=await editor.getByLabel('Root note',{exact:true}).inputValue();const naming=page.getByRole('switch',{name:'c4=60',exact:true});const before=await naming.getAttribute('aria-checked');await naming.focus();await naming.press('Space');await expect(naming).toHaveAttribute('aria-checked',before==='true'?'false':'true');await expect(editor.getByLabel('Root note',{exact:true})).toHaveValue(root);await naming.press('Enter');await expect(naming).toHaveAttribute('aria-checked',before!);
});

for(const width of [1440,390])test(`multisample empty table ${width}px browse and waveform draft cancellation`,async({page})=>{
 await page.setViewportSize({width,height:1000});await gotoWorkspace(page,'multisample');await page.getByRole('button',{name:'Table',exact:true}).click();const choosing=page.waitForEvent('filechooser');await page.getByText('no samples loaded',{exact:true}).click();await(await choosing).setFiles(tone('table-C4.wav'));await applyAudioImport(page);await expect(page.getByRole('region',{name:'Multisample instrument, 1 of 24 loaded'})).toBeVisible();await page.getByTitle('zoom and edit',{exact:true}).first().click();const zoom=page.getByRole('dialog',{name:'zoom and edit',exact:true});await zoom.getByLabel('Sample start frames').fill('200');await zoom.getByRole('button',{name:'save markers',exact:true}).click();await page.getByTitle('zoom and edit',{exact:true}).first().click();await expect(zoom.getByLabel('Sample start frames')).toHaveValue('200');await zoom.getByLabel('Sample start frames').fill('400');await zoom.press('Escape');await page.getByTitle('zoom and edit',{exact:true}).first().click();await expect(zoom.getByLabel('Sample start frames')).toHaveValue('200');await zoom.getByRole('button',{name:'cancel',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByTitle('zoom and edit',{exact:true}).first().click();await expect(zoom.getByLabel('Sample start frames')).toHaveValue('0');
});

test('organize row drops choose the intended empty pads',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await gotoWorkspace(page,'drum');await page.getByRole('button',{name:'organize',exact:true}).click();
 for(const [row,pad] of [['lower',0],['upper',1]] as const){const zone=page.getByRole('region',{name:new RegExp(`Drop zone for ${row} row`)});const file=tone(`${row}.wav`,pad);const transfer=await page.evaluateHandle(({name,bytes})=>{const data=new DataTransfer();data.items.add(new File([new Uint8Array(bytes)],name,{type:'audio/wav'}));return data;},{name:file.name,bytes:[...file.buffer]});await zone.dispatchEvent('dragover',{dataTransfer:transfer});await zone.dispatchEvent('dragleave',{dataTransfer:transfer});await zone.dispatchEvent('drop',{dataTransfer:transfer});await transfer.dispose();await applyAudioImport(page);await expect(page.getByRole('region',{name:`Drum pad instrument, ${pad+1} of 24 loaded`})).toBeVisible();await page.locator(`[data-drum-pad="${pad}"]`).click();await expect(page.getByRole('region',{name:'Focused sample editor'})).toContainText(file.name);}
});

test('wide drum MIDI audition channel persists with an isolated MIDI stub',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});
 await page.addInitScript(()=>{Object.defineProperty(navigator,'requestMIDIAccess',{configurable:true,value:async()=>Object.assign(new EventTarget(),{inputs:new Map(),outputs:new Map(),sysexEnabled:false,onstatechange:null})});});await gotoWorkspace(page,'drum');await page.getByRole('button',{name:'midi',exact:true}).click();await page.getByRole('button',{name:/connect midi devices/}).click();const channel=page.getByRole('combobox',{name:'MIDI audition channel',exact:true});await channel.selectOption('16');await expect(channel).toHaveValue('16');await expect.poll(()=>page.evaluate(()=>localStorage.getItem('midi-channel'))).toBe('16');
});

test('an empty multisample key selects the root for the nearby Add sounds chooser',async({page})=>{
 await gotoWorkspace(page,'multisample');const keyboard=page.getByRole('region',{name:'Multisample instrument, 0 of 24 loaded'});await keyboard.locator('[data-multisample-root="60"]').click();const choosing=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add sounds to MIDI 60',exact:true}).click();await(await choosing).setFiles(tone('target.wav'));await applyAudioImport(page);const editor=page.getByRole('region',{name:'Focused multisample editor'});await expect(editor.getByLabel('Root note',{exact:true})).toHaveValue('60');await expect(editor.getByRole('heading',{level:3})).toHaveText('target.wav');
});

test('sample settings waveform drag is saved once and Undo restores markers',async({page})=>{
 await gotoWorkspace(page,'drum');await page.getByRole('button',{name:'Load demo kit',exact:true}).click();await page.getByRole('button',{name:'Table',exact:true}).click();await page.getByTitle('settings',{exact:true}).first().click();const dialog=page.getByRole('dialog',{name:'sample options',exact:true});const canvas=dialog.locator('canvas').first(),box=await canvas.boundingBox();expect(box).not.toBeNull();await page.mouse.move(box!.x+1,box!.y+box!.height/2);await page.mouse.down();await page.mouse.move(box!.x+box!.width*.2,box!.y+box!.height/2,{steps:3});await page.mouse.up();await dialog.getByRole('button',{name:'save',exact:true}).click();await page.getByRole('button',{name:'Focus',exact:true}).click();const marker=page.getByRole('region',{name:'Focused sample editor'}).getByLabel('In point (seconds)',{exact:true});await expect.poll(async()=>Number(await marker.inputValue())).toBeGreaterThan(0);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(marker).toHaveValue('0');
});
