import {test,expect} from './control-audit-test';
import {gotoWorkspace,openAdvanced} from './workspace-actions';
import {applyAudioImport} from './import-helpers';
function tone(){const n=4800,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(48000,24);b.writeUInt32LE(96000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(12000*Math.sin(i/20)),44+i*2);return{name:'markers-C4.wav',mimeType:'audio/wav',buffer:b};}
for(const workspace of ['drum','multisample'] as const)test(`${workspace} zero-crossing action changes markers atomically and Undo restores them`,async({page})=>{
 await gotoWorkspace(page,workspace);
 if(workspace==='drum'){const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add sample',exact:true}).click();await(await chooser).setFiles(tone());await expect(page.getByRole('region',{name:'Drum pad instrument, 1 of 24 loaded',exact:true})).toBeVisible();}
 else{await page.getByLabel('choose multisample audio files').setInputFiles(tone());await applyAudioImport(page);}
 const editor=page.getByRole('region',{name:workspace==='drum'?'Focused sample editor':'Focused multisample editor',exact:true});const start=editor.getByRole('spinbutton',{name:/^In point/i});const end=editor.getByRole('spinbutton',{name:/^Out point/i});await start.fill('0.002');await start.blur();await end.fill('0.09');await end.blur();const before=[await start.inputValue(),await end.inputValue()];
 if(workspace==='multisample'){await editor.getByRole('button',{name:'Analyze sound',exact:true}).click();await editor.getByRole('button',{name:'Discard suggestion',exact:true}).click();await expect(editor.getByRole('button',{name:'Discard suggestion',exact:true})).toHaveCount(0);expect([await start.inputValue(),await end.inputValue()]).toEqual(before);}
 const processing=await openAdvanced(page,/Audio output and processing/);await processing.getByRole('button',{name:'auto zero crossing',exact:true}).click();await expect.poll(async()=>[await start.inputValue(),await end.inputValue()]).not.toEqual(before);expect(Number(await start.inputValue())).toBeGreaterThanOrEqual(0);expect(Number(await end.inputValue())).toBeLessThanOrEqual(.1);expect(Number(await end.inputValue())).toBeGreaterThan(Number(await start.inputValue()));await page.getByRole('button',{name:'Undo',exact:true}).click();expect([await start.inputValue(),await end.inputValue()]).toEqual(before);
 if(workspace==='drum'){await page.getByRole('button',{name:'Add demo kit',exact:true}).click();await page.getByRole('dialog',{name:'Add the demo kit'}).getByRole('button',{name:'Add to project',exact:true}).click();await page.getByRole('button',{name:'bulk edit',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('select').first().selectOption('gate');await dialog.getByRole('button',{name:/cancel/i}).click();await expect(dialog).toBeHidden();await expect(editor.getByRole('combobox',{name:'Mode',exact:true})).toHaveValue('oneshot');}
});
