import {test,expect} from './control-audit-test';
import {gotoWorkspace,projectAction,openWorkspace} from './workspace-actions';

test('Escape discards demo and library dialog drafts without changing saved content',async({page})=>{
 await gotoWorkspace(page,'drum');await page.getByRole('button',{name:'Load demo kit',exact:true}).click();const count=page.getByRole('region',{name:'Drum pad instrument, 10 of 24 loaded',exact:true});await page.getByRole('button',{name:'Add demo kit',exact:true}).click();const demo=page.getByRole('dialog',{name:'Add the demo kit'});await demo.press('Escape');await expect(demo).toBeHidden();await expect(count).toBeVisible();
 await page.getByRole('textbox',{name:'Instrument name',exact:true}).fill('Escape audit');await projectAction(page,'Save to library');await expect(page.getByText('Saved Escape audit to the library.',{exact:true})).toBeVisible();await openWorkspace(page,'library');await page.getByRole('button',{name:'New collection',exact:true}).click();const collection=page.getByRole('dialog',{name:'New collection'});await collection.getByLabel('Collection name',{exact:true}).fill('Discarded collection');await collection.press('Escape');await expect(collection).toBeHidden();await expect(page.getByText('Discarded collection',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Edit details for Escape audit',exact:true}).click();const details=page.getByRole('dialog');await details.getByLabel('Preset description',{exact:true}).fill('Discarded description');await details.press('Escape');await expect(details).toBeHidden();await page.getByRole('button',{name:'Edit details for Escape audit',exact:true}).click();await expect(details.getByLabel('Preset description',{exact:true})).not.toHaveValue('Discarded description');await details.press('Escape');
 await page.getByRole('button',{name:'delete preset',exact:true}).click();const confirmation=page.getByRole('dialog');await confirmation.locator('..').click({position:{x:3,y:3}});await expect(confirmation).toBeHidden();await expect(page.getByRole('checkbox',{name:'Select Escape audit',exact:true})).toBeVisible();
});

test('recording connection checklist and official track links are reachable without hardware',async({page,context})=>{
 await context.route(/^https:\/\//,route=>route.fulfill({status:200,body:'Isolated guide'}));await page.goto('/');await page.getByRole('button',{name:'Open capture',exact:true}).click();const capture=page.getByRole('dialog',{name:'Record takes',exact:true});const checklist=capture.locator('details').filter({has:page.locator('summary',{hasText:'Connection checklist'})});await checklist.locator('summary').click();await expect(checklist).toHaveAttribute('open','');await capture.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('navigation',{name:'Workspace'}).getByRole('button',{name:'Overview',exact:true}).click();await page.getByRole('button',{name:'Record OP-XY tracks',exact:true}).click();const tracks=page.getByRole('dialog',{name:'Record OP-XY tracks',exact:true});
 for(const name of ['Official OP-XY COM guide','Official OP-XY MIDI reference']){const link=tracks.getByRole('link',{name,exact:true}),href=await link.getAttribute('href');const opening=page.waitForEvent('popup');await link.click();const popup=await opening;await expect(popup).toHaveURL(href!);await popup.close();}
});

test('instrument and library help tooltips reveal explanations and dismiss on pointer exit',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await gotoWorkspace(page,'drum');
 for(const workspace of ['drum','multisample','library'] as const){await openWorkspace(page,workspace);if(workspace==='multisample')await page.getByRole('button',{name:'Table',exact:true}).click();const icons=page.locator('.fa-question-circle');expect(await icons.count()).toBeGreaterThan(0);for(let i=0;i<await icons.count();i++){await icons.nth(i).hover();await expect(page.locator('.enhanced-tooltip-wrapper[style*="opacity: 1"] .enhanced-tooltip-content')).toBeVisible();await expect(page.locator('.enhanced-tooltip-wrapper[style*="opacity: 1"] .enhanced-tooltip-content')).not.toHaveText('');await page.getByRole('navigation',{name:'Workspace'}).hover();await expect(page.locator('.enhanced-tooltip-wrapper[style*="opacity: 1"] .enhanced-tooltip-content')).toHaveCount(0);}}
});
