import {expect,test} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import JSZip from 'jszip';

test('generated audio through the real worklet produces reviewed WAVs and a ZIP',async({page,context,baseURL})=>{
  test.skip(!process.env.PLAYWRIGHT_STEM_FAKE_DEVICE,'Run only with the explicit synthetic-device configuration');
  test.setTimeout(60_000);
  await context.grantPermissions(['microphone'],{origin:new URL(baseURL!).origin});
  await page.addInitScript(()=>{
    const events:Array<{bytes:number[];time?:number}>=[];
    const audioFormats:MediaTrackSettings[]=[];
    Object.assign(window,{__stemReviewMidi:events,__stemReviewAudio:audioFormats});
    const originalGetUserMedia=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
    navigator.mediaDevices.getUserMedia=async constraints=>{const stream=await originalGetUserMedia(constraints);audioFormats.push(stream.getAudioTracks()[0].getSettings());return stream;};
    const output={id:'synthetic-midi',name:'Synthetic OP-XY (test only)',state:'connected',send:(bytes:number[],time?:number)=>events.push({bytes:[...bytes],time}),clear:()=>events.push({bytes:[-1]})};
    Object.defineProperty(navigator,'requestMIDIAccess',{configurable:true,value:async()=>({outputs:new Map([[output.id,output]]),addEventListener:()=>{},removeEventListener:()=>{}})});
  });
  await page.goto('/',{waitUntil:'domcontentloaded'});
  await page.getByRole('button',{name:'Record OP-XY tracks',exact:true}).click();
  const modal=page.getByRole('dialog',{name:'Record OP-XY tracks',exact:true});
  await modal.getByRole('button',{name:'Enable audio',exact:true}).click();
  await expect(modal.getByLabel('Audio input').locator('option').filter({hasText:/Fake .*Audio Input/}).first()).toBeAttached();
  const inputId=await modal.getByLabel('Audio input').locator('option').filter({hasText:/Fake .*Audio Input/}).first().getAttribute('value');
  await modal.getByLabel('Audio input').selectOption(inputId!);
  await modal.getByRole('button',{name:'Enable MIDI',exact:true}).click();
  await modal.getByLabel('MIDI output').selectOption('synthetic-midi');
  await modal.getByRole('checkbox',{name:/I understand recording/}).check();
  await modal.getByLabel('Bars (4/4)',{exact:true}).fill('1');
  await modal.getByLabel('Tail seconds',{exact:true}).fill('0');
  await modal.getByLabel('Track 1 name',{exact:true}).fill('Kick / test');
  expect(await page.evaluate(()=>Reflect.get(window,'__stemReviewMidi').length)).toBe(0);
  await modal.getByRole('button',{name:'Record test',exact:true}).click();
  const first=modal.getByRole('group',{name:'Reviewed track 1',exact:true});
  await expect(first).toBeVisible({timeout:20_000});
  await expect(first).toContainText('2.00 s');
  await expect(modal.getByRole('button',{name:'Record selected',exact:true})).toBeEnabled();
  await modal.getByRole('checkbox',{name:'Track 2',exact:true}).check();
  await modal.getByRole('button',{name:'Record selected',exact:true}).click();
  await expect(modal.getByRole('group',{name:'Reviewed track 2',exact:true})).toBeVisible({timeout:25_000});
  await expect(modal.getByRole('group',{name:'Reviewed track 1',exact:true})).toHaveCount(1);
  await expect(modal.getByRole('button',{name:'Record selected',exact:true})).toBeEnabled();
  const wavEvent=page.waitForEvent('download');
  await first.getByRole('button',{name:'Download WAV',exact:true}).click();
  const wav=await wavEvent;expect(wav.suggestedFilename()).toBe('Kick-test.wav');
  const bytes=await readFile((await wav.path())!);
  expect(bytes.toString('ascii',0,4)).toBe('RIFF');
  let cursor=12,rate=0,channels=0,bits=0,dataBytes=0;
  while(cursor+8<=bytes.length){const tag=bytes.toString('ascii',cursor,cursor+4),size=bytes.readUInt32LE(cursor+4);if(tag==='fmt '){channels=bytes.readUInt16LE(cursor+10);rate=bytes.readUInt32LE(cursor+12);bits=bytes.readUInt16LE(cursor+22);}if(tag==='data')dataBytes=size;cursor+=8+size+(size%2);}
  const actualInput=await page.evaluate(()=>Reflect.get(window,'__stemReviewAudio').at(-1) as MediaTrackSettings);
  expect({rate,channels,bits}).toEqual({rate:actualInput.sampleRate,channels:actualInput.channelCount,bits:24});
  expect(dataBytes/(channels*bits/8)).toBe(rate*2);
  await modal.getByLabel('BPM',{exact:true}).fill('100');
  const zipEvent=page.waitForEvent('download');await modal.getByRole('button',{name:'Download all ZIP',exact:true}).click();
  const zipDownload=await zipEvent,zip=await JSZip.loadAsync(await readFile((await zipDownload.path())!));
  const manifest=JSON.parse(await zip.file('manifest.json')!.async('string'));
  expect(manifest.tracks).toHaveLength(2);
  expect(manifest.tracks.map((track:{settings:{bpm:number}})=>track.settings.bpm)).toEqual([120,120]);
  expect(manifest.tracks.every((track:{frames:number;sampleRate:number})=>track.frames===track.sampleRate*2)).toBe(true);
  await first.getByRole('button',{name:'Slice this recording',exact:true}).click();
  const slicer=page.getByRole('dialog',{name:'slice audio',exact:true});await expect(slicer).toBeVisible();
  await page.keyboard.press('Escape');await expect(slicer).toHaveCount(0);await expect(first).toBeVisible();
  await modal.getByRole('button',{name:'Close',exact:true}).last().click();
  const discard=page.getByRole('alertdialog',{name:'Discard reviewed recordings?',exact:true});
  await expect(discard).toBeVisible();
  await expect(discard.getByRole('button',{name:'Keep reviewing',exact:true})).toBeFocused();
  await page.keyboard.press('Escape');await expect(discard).toHaveCount(0);await expect(first).toBeVisible();
  const events=await page.evaluate(()=>Reflect.get(window,'__stemReviewMidi') as Array<{bytes:number[]}>);
  expect(events.filter(event=>event.bytes[0]===0xfa)).toHaveLength(3);
  expect(events.filter(event=>event.bytes[0]>=0xb0&&event.bytes[0]<=0xbf).every(event=>event.bytes[0]<=0xb7&&event.bytes[1]===9)).toBe(true);
});
