import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { useAppContext } from '../../context/AppContext';
import { captureExternalTransfer, captureFileList, resolveCapturedTransfer, type CapturedExternalTransfer, type IntakeIssue } from '../../utils/externalFileIntake';
import { prepareAudioImportFiles, proposeDrumDestinations, type ImportDestination, type PreparedImportAsset } from '../../utils/audioImport';
import type { ExpectedAssetIdentity } from '../../utils/recordingApplication';
import { AudioImportContext, type AudioImportIntent } from './AudioImportContext';
import { useOwnedDialog } from '../../hooks/useOwnedDialog';

type ReviewRow={asset:PreparedImportAsset;reason:string;destination:string;rootNote:number;include:boolean;expected?:ExpectedAssetIdentity;replacementTarget?:ExpectedAssetIdentity};
type Review={operationId:string;instrument:'drum'|'multisample';expectedProjectGeneration:number;rows:ReviewRow[];issues:IntakeIssue[]};

function intentFromElement(target:EventTarget|null):AudioImportIntent|null {
  const element=target instanceof Element?target.closest<HTMLElement>('[data-audio-import]'):null;if(!element)return null;
  const instrument=element.dataset.audioImport;if(instrument!=='drum'&&instrument!=='multisample')return null;
  const pads=element.dataset.drumPads?.split(',').map(Number).filter(Number.isInteger);
  const start=Number(element.dataset.drumPadStart),single=Number(element.dataset.drumPad),root=Number(element.dataset.multisampleRoot);
  return {instrument,drumPads:pads?.length?pads:Number.isInteger(start)?Array.from({length:24-start},(_,index)=>start+index):Number.isInteger(single)?[single]:undefined,multisampleRoot:Number.isInteger(root)?root:undefined};
}

export function AudioImportProvider({children}:{children:ReactNode}) {
  const {state,dispatch}=useAppContext();const stateRef=useRef(state);stateRef.current=state;
  const dialogRef=useRef<HTMLDivElement>(null),returnFocusRef=useRef<HTMLElement|null>(null);
  const generation=useRef(0),abort=useRef<AbortController|null>(null),ownedProjectGeneration=useRef<number|null>(null),pendingCommit=useRef<string|null>(null),applySerial=useRef(0);const [phase,setPhase]=useState<'idle'|'resolving'|'preparing'|'review'|'applying'>('idle');
  const [progress,setProgress]=useState({discovered:0,prepared:0,rejected:0,capacityExcess:0});const [review,setReview]=useState<Review|null>(null);const [error,setError]=useState<string|null>(null);const [directPad,setDirectPad]=useState(false);
  const cancel=useCallback(()=>{generation.current++;abort.current?.abort();abort.current=null;ownedProjectGeneration.current=null;pendingCommit.current=null;setPhase('idle');setReview(null);setError(null);setDirectPad(false);setProgress({discovered:0,prepared:0,rejected:0,capacityExcess:0});},[]);
  const start=useCallback((captured:CapturedExternalTransfer,intent:AudioImportIntent)=>{if(captured.kind==='internal')return;generation.current++;const owned=generation.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;
    returnFocusRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;
    const directCandidate=intent.instrument==='drum'&&intent.drumPads?.length===1&&!intent.drumReplacement&&!intent.drumPadReplacement;
    const expectedProjectGeneration=stateRef.current.projectGeneration??0;ownedProjectGeneration.current=expectedProjectGeneration;pendingCommit.current=null;setReview(null);setError(null);setDirectPad(Boolean(directCandidate));setPhase('resolving');
    void (async()=>{try{const resolved=await resolveCapturedTransfer(captured,controller.signal);if(owned!==generation.current||(stateRef.current.projectGeneration??0)!==expectedProjectGeneration)return;setPhase('preparing');
      const currentAssets=[...stateRef.current.drumSamples,...stateRef.current.multisampleFiles];const replacement=intent.drumReplacement,padReplacement=intent.drumPadReplacement;
      const replacementIdentity=replacement??padReplacement?.expected;
      const padTarget=padReplacement?stateRef.current.drumSamples[padReplacement.padIndex]:undefined;
      const replacementIsCurrent=padReplacement?padTarget?.file===padReplacement.expected.file&&padTarget?.audioBuffer===padReplacement.expected.audioBuffer:replacement&&currentAssets.some(item=>item.file===replacement.file&&item.audioBuffer===replacement.audioBuffer);
      const existingDecodedBytes=currentAssets.reduce((sum,item)=>sum+(item.audioBuffer?24+4*item.audioBuffer.numberOfChannels*item.audioBuffer.length:0),0)
        -(replacementIsCurrent&&replacementIdentity?.audioBuffer?24+4*replacementIdentity.audioBuffer.numberOfChannels*replacementIdentity.audioBuffer.length:0);
      const prepared=await prepareAudioImportFiles(resolved.files,intent.instrument,expectedProjectGeneration,stateRef.current.midiNoteMapping,controller.signal,value=>{if(owned===generation.current)setProgress({discovered:value.discovered,prepared:value.prepared,rejected:value.rejected,capacityExcess:value.capacityExcess});},undefined,{existingDecodedBytes});
      if(owned!==generation.current||(stateRef.current.projectGeneration??0)!==expectedProjectGeneration)return;const occupiedDrums=stateRef.current.drumSamples;
      const requestedPads=new Map<string,number>();resolved.files.forEach((record,index)=>{const pad=intent.drumPads?.[record.sourceOrdinal??index];if(pad!==undefined)requestedPads.set(record.id,pad);});
      const explicitPads=new Map<string,number>(),reservedPads=new Set<number>();
      if(intent.instrument==='drum')for(const asset of prepared.assets){const pad=requestedPads.get(asset.id);if(pad!==undefined&&Number.isInteger(pad)&&pad>=0&&pad<24&&!occupiedDrums[pad]?.isLoaded&&!reservedPads.has(pad)){explicitPads.set(asset.id,pad);reservedPads.add(pad);}}
      const suggestedAssets=prepared.assets.filter(asset=>!requestedPads.has(asset.id));const suggested=proposeDrumDestinations(suggestedAssets,occupiedDrums,reservedPads);const proposals=new Map(suggested.map(item=>[item.id,item]));
      const usedRoots=new Set(stateRef.current.multisampleFiles.map(file=>file.rootNote));const reservedRoots=new Set<number>();
      const rows=prepared.assets.map((asset,index):ReviewRow=>{if(intent.instrument==='drum'){if(index===0&&replacement)return {asset,reason:'replace the selected unassigned sound after review',destination:'replace-selected',rootNote:60,include:true,expected:replacement,replacementTarget:replacement};if(index===0&&padReplacement){const {padIndex,expected}=padReplacement,current=occupiedDrums[padIndex];const same=Number.isInteger(padIndex)&&padIndex>=0&&padIndex<24&&current?.isLoaded&&current.file===expected.file&&current.audioBuffer===expected.audioBuffer;return {asset,reason:same?'replace the selected pad after review':'selected pad changed while import was preparing; choose a destination',destination:same?`replace:${padIndex}`:'unassigned',rootNote:60,include:true,expected:same?expected:undefined};}const requested=requestedPads.get(asset.id),explicit=explicitPads.get(asset.id),proposal=proposals.get(asset.id);const proposed=explicit??proposal?.destination??null;const available=proposed!==null&&!occupiedDrums[proposed]?.isLoaded;
          return {asset,reason:requested!==undefined?(explicit!==undefined?'chosen drop pad':'chosen drop pad is occupied or already reserved; kept unassigned'):(proposal?.reason??'no confident filename match'),destination:available?`pad:${proposed}`:'unassigned',rootNote:60,include:true};}
        const suggested=index===0&&intent.multisampleRoot!==undefined?intent.multisampleRoot:asset.metadata.midiNote;const usable=Number.isInteger(suggested)&&suggested>=0&&suggested<=127&&!usedRoots.has(suggested)&&!reservedRoots.has(suggested);if(usable)reservedRoots.add(suggested);
        return {asset,reason:usable?'note detected from destination or filename':'choose an unused root note',destination:usable?'root':'unassigned',rootNote:Number.isInteger(suggested)&&suggested>=0&&suggested<=127?suggested:60,include:usable};});
      const issues=[...resolved.failed,...resolved.unsupported,...prepared.rejected.map(item=>({name:item.path,reason:item.reason})),...prepared.excess.map(item=>({name:item.path,reason:item.reason}))];
      const nextReview={operationId:captured.operationId,instrument:intent.instrument,expectedProjectGeneration,rows,issues};setReview(nextReview);
      const onlyRow=rows[0];
      if(directCandidate&&resolved.files.length===1&&rows.length===1&&issues.length===0&&onlyRow.destination===`pad:${intent.drumPads![0]}`){
        const commitId=`${captured.operationId}-apply-${++applySerial.current}`;pendingCommit.current=commitId;setPhase('applying');
        dispatch({type:'COMMIT_PREPARED_IMPORTS',payload:{operationId:commitId,prepared:{instrument:'drum',expectedProjectGeneration,assets:[onlyRow.asset],selections:[{id:onlyRow.asset.id,destination:{kind:'drum-pad',padIndex:intent.drumPads![0],decision:'choose-empty'}}]}}});
      }else {setDirectPad(false);setPhase('review');}
    }catch(reason){if(owned!==generation.current||controller.signal.aborted)return;setDirectPad(false);setError(reason instanceof Error?reason.message:'Import preparation failed');setPhase('review');}})();
  },[dispatch]);
  const beginFiles=useCallback((files:ArrayLike<File>,intent:AudioImportIntent)=>start(captureFileList(files),intent),[start]);
  const beginDrop=useCallback((transfer:DataTransfer,intent:AudioImportIntent)=>start(captureExternalTransfer(transfer),intent),[start]);
  useEffect(()=>{const onDrop=(event:DragEvent)=>{const intent=intentFromElement(event.target);if(!intent||!event.dataTransfer)return;const captured=captureExternalTransfer(event.dataTransfer);if(captured.kind==='internal')return;event.preventDefault();event.stopImmediatePropagation();start(captured,intent);};document.addEventListener('drop',onDrop,true);return()=>document.removeEventListener('drop',onDrop,true)},[start]);
  useEffect(()=>{if(ownedProjectGeneration.current!==null&&(state.projectGeneration??0)!==ownedProjectGeneration.current)cancel()},[cancel,state.projectGeneration]);
  useEffect(()=>()=>{generation.current++;abort.current?.abort()},[]);
  useEffect(()=>{const receipt=state.importCommitResult;if(!review||!receipt||receipt.operationId!==pendingCommit.current)return;pendingCommit.current=null;if(receipt.status==='rejected'){setDirectPad(false);setPhase('review');setError(receipt.error??'Import was rejected');return;}const applied=new Set(receipt.appliedIds??[]);setReview(current=>{if(!current)return current;const remaining=current.rows.filter(row=>!applied.has(row.asset.id));if(remaining.length){setDirectPad(false);setPhase('review');return {...current,rows:remaining};}queueMicrotask(cancel);return current;});},[cancel,review,state.importCommitResult]);
  const apply=()=>{if(!review)return;const selections=review.rows.filter(row=>row.include).map(row=>{let destination:ImportDestination;if(review.instrument==='drum'){
      if(row.destination==='unassigned')destination={kind:'drum-unassigned'};else if(row.destination==='replace-selected'&&row.replacementTarget)destination={kind:'drum-asset',decision:'replace',expected:row.replacementTarget};else {const [decisionText,indexText]=row.destination.split(':');const padIndex=Number(indexText);destination=decisionText==='replace'?{kind:'drum-pad',padIndex,decision:'replace',expected:row.expected}:{kind:'drum-pad',padIndex,decision:'choose-empty'};}}
    else {if(row.destination==='unassigned')return null;destination=row.destination==='replace'?{kind:'multisample-root',rootNote:row.rootNote,decision:'replace',expected:row.expected}:{kind:'multisample-root',rootNote:row.rootNote,decision:'choose-free'};}
    return {id:row.asset.id,destination};}).filter((item):item is NonNullable<typeof item>=>Boolean(item));if(!selections.length){setError('Select at least one file to apply');return;}const commitId=`${review.operationId}-apply-${++applySerial.current}`;pendingCommit.current=commitId;dispatch({type:'COMMIT_PREPARED_IMPORTS',payload:{operationId:commitId,prepared:{instrument:review.instrument,expectedProjectGeneration:review.expectedProjectGeneration,assets:review.rows.map(row=>row.asset),selections}}});};
  const update=(id:string,patch:Partial<ReviewRow>)=>setReview(current=>current?{...current,rows:current.rows.map(row=>row.asset.id===id?{...row,...patch}:row)}:current);
  const value=useMemo(()=>({beginFiles,beginDrop}),[beginDrop,beginFiles]);
  useOwnedDialog({active:phase!=='idle'&&!directPad,dialogRef,onClose:cancel,returnFocus:returnFocusRef.current});
  return <AudioImportContext.Provider value={value}>{children}{phase!=='idle'&&directPad&&<div role="status" style={{position:'fixed',bottom:20,right:20,zIndex:10000,padding:'10px 14px',background:'var(--studio-panel)',border:'1px solid var(--studio-border)',color:'var(--studio-text)'}}>Adding sample to selected pad…</div>}{phase!=='idle'&&!directPad&&<div ref={dialogRef} role="dialog" aria-modal="true" aria-label="Import audio" tabIndex={-1} style={{position:'fixed',inset:'8%',zIndex:10000,overflow:'auto',background:'var(--color-bg-primary)',border:'1px solid var(--color-border-medium)',borderRadius:8,padding:24,boxShadow:'0 8px 30px rgba(0,0,0,.3)'}}>
    <h2 style={{marginTop:0}}>Import audio</h2>{phase!=='review'&&<p role="status">{phase==='resolving'?'Reading dropped files and folders…':`Preparing ${progress.prepared+progress.rejected+progress.capacityExcess} of ${progress.discovered} files…`}</p>}
    {error&&<p role="alert">{error}</p>}{review&&<><p>{review.rows.length} decoded file{review.rows.length===1?'':'s'} ready for review. Browser import keeps original bytes; OP-XY export uses the output format selected below the instrument.</p>
      {review.issues.length>0&&<div role="status"><strong>{review.issues.length} item{review.issues.length===1?'':'s'} could not be prepared</strong><ul>{review.issues.map((issue,index)=><li key={`${issue.name}-${index}`}>{issue.name}: {issue.reason}</li>)}</ul></div>}
      <ul style={{padding:0,listStyle:'none'}}>{review.rows.map(row=><li key={row.asset.id} style={{padding:'12px 0',borderBottom:'1px solid var(--color-border-subtle)'}}>
        <label><input aria-label={`Include ${row.asset.file.name}`} type="checkbox" checked={row.include} onChange={event=>update(row.asset.id,{include:event.target.checked})}/> {row.asset.file.name}</label>
        <div>{row.asset.metadata.format.toUpperCase()} source · source bit depth {row.asset.metadata.bitDepth===undefined?'unknown':`${row.asset.metadata.bitDepth}-bit`} · source rate {row.asset.metadata.sourceSampleRate===undefined?'unknown':`${row.asset.metadata.sourceSampleRate} Hz`} · source channels {row.asset.metadata.sourceChannels===undefined?'unknown':row.asset.metadata.sourceChannels} · decoded {row.asset.audioBuffer.sampleRate} Hz / {row.asset.audioBuffer.numberOfChannels} ch</div><div>{row.reason}</div>
        {review.instrument==='drum'?<select aria-label={`Destination for ${row.asset.file.name}`} value={row.destination} onChange={event=>{const destination=event.target.value;if(destination==='replace-selected')update(row.asset.id,{destination,expected:row.replacementTarget});else if(destination.startsWith('replace:')){const current=stateRef.current.drumSamples[Number(destination.split(':')[1])];update(row.asset.id,{destination,expected:{file:current?.file??null,audioBuffer:current?.audioBuffer??null}});}else update(row.asset.id,{destination,expected:undefined});}}>
          <option value="unassigned">Keep unassigned</option>{row.replacementTarget&&<option value="replace-selected">Replace selected unassigned sound</option>}{state.drumSamples.slice(0,24).map((sample,index)=><option key={index} value={sample?.isLoaded?`replace:${index}`:`pad:${index}`}>{sample?.isLoaded?`Replace pad ${index+1}`:`Pad ${index+1}`}</option>)}</select>
        :<><label> Root note <input aria-label={`Root note for ${row.asset.file.name}`} type="number" min={0} max={127} value={row.rootNote} onChange={event=>{const rootNote=Number(event.target.value),occupied=stateRef.current.multisampleFiles.some(file=>file.rootNote===rootNote);update(row.asset.id,{rootNote,destination:occupied?'unassigned':'root',expected:undefined});}}/></label><select aria-label={`Assignment for ${row.asset.file.name}`} value={row.destination} onChange={event=>{const destination=event.target.value;if(destination==='replace'){const current=stateRef.current.multisampleFiles.find(file=>file.rootNote===row.rootNote);update(row.asset.id,{destination,include:true,expected:{file:current?.file??null,audioBuffer:current?.audioBuffer??null}});}else update(row.asset.id,{destination,expected:undefined});}}><option value="unassigned">Keep for review</option>{!state.multisampleFiles.some(file=>file.rootNote===row.rootNote)&&<option value="root">Use empty root note</option>}{state.multisampleFiles.some(file=>file.rootNote===row.rootNote)&&<option value="replace">Replace current root note</option>}</select></>}
      </li>)}</ul><button onClick={apply}>Apply import</button> </>}
    <button onClick={cancel}>Cancel import</button>
  </div>}</AudioImportContext.Provider>;
}
