import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {WebMidi} from 'webmidi';
import {AutoSampler,noteSequence,validateAutoSampleSettings,type AutoCapture,type AutoCaptureCallbacks,type AutoSampleResult,type AutoSampleSettings} from '../../audio/recording/autoSampler';
import {RECORDING_LIMITS} from '../../audio/recording/captureSession';
import {midiRoutes,type RouteLease} from '../../midi/routeLease';

interface AudioDevice {deviceId:string;label:string}
export type GuidedSamplingStep='connect'|'capture'|'review'|'finish';
interface Props {audioDeviceId:string;audioDevices?:AudioDevice[];audioSelectionVersion?:number;onAudioDeviceChange?:(id:string)=>void;onExplicitAudioDeviceChange?:(id:string)=>void;disabled:boolean;retainedCount:number;retainedBytes:number;existingRoots:number[];createCapture:(callbacks:AutoCaptureCallbacks)=>AutoCapture;onTake:(result:AutoSampleResult,replaceRoot:boolean)=>void;onRunningChange:(running:boolean)=>void;guidedStep?:GuidedSamplingStep;onGuidedStepChange?:(step:GuidedSamplingStep)=>void;onCaptureReview?:()=>void;onAuditionCheck?:(buffer:AudioBuffer)=>void;onStopAudition?:()=>void;onCheckBytesChange?:(bytes:number)=>void;previewActive?:boolean;initialFocus?:boolean}
type Profile='custom'|'nina-digitakt'|'ableton';
interface RouteConfig {audioDeviceId:string;outputId:string;settings:AutoSampleSettings}
interface Preferences {profile:Profile;routes:Record<Profile,RouteConfig>}
interface CheckEvidence {routeKey:string;audioBuffer:AudioBuffer;rootNote:number;level:string}
const defaults:AutoSampleSettings={startNote:48,endNote:72,step:6,velocity:100,channel:1,holdSeconds:1,tailSeconds:1,settleSeconds:.25,readinessTimeoutSeconds:2};
const blankRoute=():RouteConfig=>({audioDeviceId:'',outputId:'',settings:{...defaults}});
const storageKey='op-patchstudio:auto-sampling:v1';
const profiles=['custom','nina-digitakt','ableton'] as const;
const button:React.CSSProperties={minHeight:44,padding:'0.5rem 0.75rem',border:'1px solid var(--color-border-medium, #bbb)',borderRadius:4,background:'var(--color-bg-primary, #fff)',color:'inherit'};
const noop=()=>{};

function loadPreferences():Preferences {const fallback:Preferences={profile:'custom',routes:{custom:blankRoute(),'nina-digitakt':blankRoute(),ableton:blankRoute()}};try{const value=JSON.parse(localStorage.getItem(storageKey)||'null') as Partial<Preferences>|null;if(!value?.routes)return fallback;for(const profile of profiles){const route=value.routes[profile];if(route)fallback.routes[profile]={audioDeviceId:typeof route.audioDeviceId==='string'?route.audioDeviceId:'',outputId:typeof route.outputId==='string'?route.outputId:'',settings:{...defaults,...route.settings}};}if(typeof value.profile==='string'&&profiles.includes(value.profile as Profile))fallback.profile=value.profile as Profile;}catch{/* storage is optional */}return fallback;}
function profileHelp(profile:Profile){if(profile==='nina-digitakt')return 'Example: connect the hardware MIDI route and select the browser audio input carrying its return.';if(profile==='ableton')return 'Example: route browser MIDI into the DAW and return that instrument through a browser audio input.';return 'Choose the MIDI destination and the audio return that carry the same hardware or software instrument.';}
function peakLevel(result:AutoSampleResult){let peak=0;const buffer=result.take.audioBuffer;for(let channel=0;channel<buffer.numberOfChannels;channel++){const data=buffer.getChannelData(channel);for(let frame=0;frame<result.take.frames;frame++)peak=Math.max(peak,Math.abs(data[frame]));}return peak;}
function levelLabel(peak:number){return `${(20*Math.log10(Math.max(peak,1e-6))).toFixed(1)} dBFS peak`;}
const setupSteps:Record<Profile,string[]>={custom:['Select the connected MIDI output and the audio input carrying the same instrument.','Run Check sound, audition its captured return, and confirm it is the intended instrument.'],'nina-digitakt':['Connect the hardware MIDI route and choose its connected output.','Route the hardware audio to the computer and select that browser input.','Check and audition one note before capturing the range.'],ableton:['Create a MIDI route from the browser to the intended software instrument.','Return that instrument through a virtual audio input or audio interface.','Check and audition one note before capturing the range.']};

interface CleanupBarrier {track:<T>(operation:Promise<T>)=>Promise<T>;wait:()=>Promise<void>}
function createCleanupBarrier():CleanupBarrier {const pending=new Set<Promise<unknown>>();return{track:<T,>(operation:Promise<T>)=>{const tracked=operation.finally(()=>pending.delete(tracked));pending.add(tracked);return tracked;},wait:async()=>{while(pending.size)await Promise.allSettled([...pending]);}};}
function joinAutoCaptureCleanup(capture:AutoCapture,barrier:CleanupBarrier):AutoCapture {let stopping:Promise<void>|undefined,disposing:Promise<void>|undefined;return{enableInput:deviceId=>capture.enableInput(deviceId),start:()=>capture.start(),stop:()=>stopping??=barrier.track(capture.stop()),dispose:()=>disposing??=barrier.track(capture.dispose())};}

export function AutoSamplingPanel(props:Props){
  const {audioDeviceId,audioDevices=[],audioSelectionVersion=0,onAudioDeviceChange=noop,onExplicitAudioDeviceChange=onAudioDeviceChange,disabled,retainedCount,retainedBytes,existingRoots,createCapture,onTake,onRunningChange,guidedStep,onGuidedStepChange,onCaptureReview,onAuditionCheck,onStopAudition=noop,onCheckBytesChange=noop,previewActive=false}=props;
  const guided=guidedStep!==undefined;
  const parentAccountsForCheck=props.onCheckBytesChange!==undefined;
  const saved=useMemo(loadPreferences,[]),initial=saved.routes[saved.profile],[profile,setProfile]=useState<Profile>(saved.profile),[outputId,setOutputId]=useState(initial.outputId),[settings,setSettings]=useState(initial.settings);
  const [outputs,setOutputs]=useState<Array<{id:string;name:string}>>([]),[midiEnabled,setMidiEnabled]=useState(WebMidi.enabled),[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[retryNotes,setRetryNotes]=useState<number[]>([]),[inputResolutionRequired,setInputResolutionRequired]=useState(false),[checkEvidence,setCheckEvidence]=useState<CheckEvidence|undefined>(),[heardConfirmed,setHeardConfirmed]=useState(false);
  const routesRef=useRef(saved.routes),samplerRef=useRef<AutoSampler|undefined>(undefined),leaseRef=useRef<RouteLease|undefined>(undefined),cleanupBarrierRef=useRef<CleanupBarrier|undefined>(undefined),stopOperationRef=useRef<Promise<void>|undefined>(undefined),retryRef=useRef<number|undefined>(undefined),mountedRef=useRef(true),runIdRef=useRef(0),evidenceGenerationRef=useRef(0),runTakeCountRef=useRef(0),checkBytesRef=useRef(0),desiredAudioRef=useRef<string|null>(initial.audioDeviceId||null),audioSelectionVersionRef=useRef(audioSelectionVersion),routeKeyRef=useRef('');
  const invalidateCheck=useCallback(()=>{evidenceGenerationRef.current+=1;checkBytesRef.current=0;onCheckBytesChange(0);setCheckEvidence(undefined);setHeardConfirmed(false);onStopAudition();},[onCheckBytesChange,onStopAudition]);
  const connectedOutputs=useCallback(()=>WebMidi.outputs.filter(output=>output.state==='connected').map(output=>({id:output.id,name:output.name||'Unnamed MIDI output'})),[]);
  const refreshOutputs=useCallback(()=>{if(!WebMidi.enabled)return;const next=connectedOutputs();setOutputs(next);if(outputId&&!next.some(output=>output.id===outputId)){setOutputId('');setError('The saved MIDI output is unavailable. Choose a connected output.');}},[connectedOutputs,outputId]);
  useEffect(()=>{if(midiEnabled)refreshOutputs();},[midiEnabled,refreshOutputs]);
  useEffect(()=>{if(audioSelectionVersion!==audioSelectionVersionRef.current){audioSelectionVersionRef.current=audioSelectionVersion;desiredAudioRef.current=null;setInputResolutionRequired(false);invalidateCheck();}},[audioSelectionVersion,invalidateCheck]);
  useEffect(()=>{const desired=desiredAudioRef.current;if(!desired)return;if(audioDeviceId===desired){desiredAudioRef.current=null;return;}if(!audioDevices.length)return;if(audioDevices.some(device=>device.deviceId===desired))onAudioDeviceChange(desired);else{setInputResolutionRequired(true);onAudioDeviceChange('');setError('The saved audio input is unavailable. Choose an input before capture.');}},[audioDeviceId,audioDevices,onAudioDeviceChange]);
  useEffect(()=>{if(desiredAudioRef.current&&audioDeviceId!==desiredAudioRef.current)return;routesRef.current={...routesRef.current,[profile]:{audioDeviceId,outputId,settings}};try{localStorage.setItem(storageKey,JSON.stringify({profile,routes:routesRef.current} satisfies Preferences));}catch{/* capture remains available */}},[audioDeviceId,outputId,profile,settings]);
  useEffect(()=>{mountedRef.current=true;return()=>{mountedRef.current=false;runIdRef.current+=1;evidenceGenerationRef.current+=1;checkBytesRef.current=0;onCheckBytesChange(0);onStopAudition();const sampler=samplerRef.current,lease=leaseRef.current,barrier=cleanupBarrierRef.current;if(sampler)void(async()=>{try{await sampler.cancel();}finally{await barrier?.wait();lease?.release();if(leaseRef.current===lease)leaseRef.current=undefined;if(cleanupBarrierRef.current===barrier)cleanupBarrierRef.current=undefined;}})();else{lease?.release();if(leaseRef.current===lease)leaseRef.current=undefined;if(cleanupBarrierRef.current===barrier)cleanupBarrierRef.current=undefined;}};},[onCheckBytesChange,onStopAudition]);
  const setNumber=(key:keyof AutoSampleSettings,value:number)=>setSettings(current=>({...current,[key]:value}));
  const enableMidi=async()=>{setError('');try{if(!WebMidi.enabled)await WebMidi.enable();if(!mountedRef.current)return;setMidiEnabled(true);const next=connectedOutputs();setOutputs(next);if(outputId&&!next.some(output=>output.id===outputId)){setOutputId('');setError('The saved MIDI output is unavailable. Choose a connected output.');}}catch(reason){if(mountedRef.current)setError(`${reason instanceof Error?reason.message:'MIDI permission was denied.'} Allow MIDI access in the browser, then retry.`);}};
  // End note and spacing choose the later range; every setting affecting the checked sound invalidates evidence.
  const routeKey=[profile,audioDeviceId,outputId,settings.channel,settings.velocity,settings.startNote,settings.holdSeconds,settings.tailSeconds,settings.settleSeconds,settings.readinessTimeoutSeconds].join('|');
  routeKeyRef.current=routeKey;
  useEffect(()=>{invalidateCheck();setProgress('');},[invalidateCheck,routeKey]);
  const checkReady=checkEvidence?.routeKey===routeKey&&(!guided||heardConfirmed);
  const begin=async(onlyNote?:number,replace=false,checkSound=false)=>{if(samplerRef.current||stopOperationRef.current)return;setError('');if(checkSound){invalidateCheck();setProgress('');}else onStopAudition();let notes:number[];let sampler:AutoSampler|undefined,pendingCheck:CheckEvidence|undefined,lease:RouteLease|undefined,barrier:CleanupBarrier|undefined;const runId=++runIdRef.current,evidenceGeneration=evidenceGenerationRef.current,runRouteKey=routeKey;runTakeCountRef.current=0;try{notes=onlyNote===undefined?validateAutoSampleSettings(settings):[onlyNote];if(checkSound){const estimatedCheck=Math.ceil((settings.holdSeconds+settings.tailSeconds)*48_000)*2*4;if(retainedBytes+estimatedCheck>RECORDING_LIMITS.ownedBytes)throw new Error('The 256 MiB recording budget does not have room for a sound check.');}else{const conflict=notes.find(note=>existingRoots.includes(note)&&!(replace&&note===onlyNote));if(conflict!==undefined)throw new Error(`MIDI root ${conflict} is already occupied. Resolve the destination before capture.`);if(retainedCount+notes.length>RECORDING_LIMITS.takes)throw new Error('The review tray does not have room for this range.');const estimated=notes.length*Math.ceil((settings.holdSeconds+settings.tailSeconds)*48_000)*2*8,checkBytes=parentAccountsForCheck?0:checkBytesRef.current;if(retainedBytes+checkBytes+estimated>RECORDING_LIMITS.ownedBytes)throw new Error('The 256 MiB recording budget does not have room for this range and its retained sound check.');if((onlyNote===undefined&&(guided||profile!=='custom')||guided&&replace)&&!checkReady)throw new Error('Check sound, audition it, and confirm the intended instrument before capturing with the current settings.');}if(inputResolutionRequired||desiredAudioRef.current)throw new Error('Choose an audio input after the saved device could not be found.');if(!midiEnabled)throw new Error('Enable MIDI from this panel before starting automatic capture.');const output=WebMidi.getOutputById(outputId);if(!output||output.state!=='connected')throw new Error('Choose a connected MIDI output before starting.');lease=midiRoutes.acquire(outputId,'autosampling');if(!lease)throw new Error('This MIDI output is busy with Devices or track capture.');
      barrier=createCleanupBarrier();leaseRef.current=lease;cleanupBarrierRef.current=barrier;setRunning(true);onRunningChange(true);setProgress(`Preparing MIDI note ${notes[0]}...`);retryRef.current=replace?onlyNote:undefined;
      sampler=new AutoSampler({createCapture:callbacks=>joinAutoCaptureCleanup(createCapture(callbacks),barrier!),midi:{isConnected:()=>WebMidi.getOutputById(outputId)?.state==='connected',noteOn:(note,velocity,channel)=>output.send([0x90|(channel-1),note,velocity]),noteOff:(note,channel)=>output.send([0x80|(channel-1),note,0])},onTake:result=>{if(runId!==runIdRef.current)return;if(checkSound){const peak=peakLevel(result),level=levelLabel(peak);if(result.selected&&Number.isFinite(peak)&&peak>=.02&&peak<.99&&routeKeyRef.current===runRouteKey&&evidenceGenerationRef.current===evidenceGeneration)pendingCheck={routeKey:runRouteKey,audioBuffer:result.take.audioBuffer,rootNote:result.rootNote,level};else if(evidenceGenerationRef.current===evidenceGeneration){invalidateCheck();const concern=result.warnings.length?result.warnings.join(' '):peak<.02?'The audio return is too quiet.':'The audio return is near clipping.';setError(`Sound check needs attention: ${level}. ${concern}`);}return;}runTakeCountRef.current+=1;const replacing=retryRef.current===result.rootNote;if(!replacing||result.selected)onTake(result,replacing);setRetryNotes(current=>result.warnings.length?[...new Set([...current,result.rootNote])]:current.filter(note=>note!==result.rootNote));},onProgress:(completed,total,note)=>{if(runId===runIdRef.current&&!checkSound)setProgress(`Captured ${completed}/${total}: MIDI note ${note}.`);},onError:message=>{if(runId===runIdRef.current){if(checkSound)invalidateCheck();setError(message);}}});samplerRef.current=sampler;await sampler.run(settings,audioDeviceId,onlyNote);if(checkSound&&pendingCheck&&runId===runIdRef.current&&routeKeyRef.current===runRouteKey&&evidenceGenerationRef.current===evidenceGeneration){const bytes=pendingCheck.audioBuffer.length*pendingCheck.audioBuffer.numberOfChannels*4;checkBytesRef.current=bytes;onCheckBytesChange(bytes);setCheckEvidence(pendingCheck);setHeardConfirmed(false);setProgress(`Sound check passed on MIDI note ${pendingCheck.rootNote}: ${pendingCheck.level}. Audition the check note and confirm what you heard.`);}else if(checkSound&&evidenceGenerationRef.current===evidenceGeneration)invalidateCheck();
    }catch(reason){if(runId===runIdRef.current){if(checkSound)invalidateCheck();setError(reason instanceof Error?reason.message:String(reason));}}finally{await barrier?.wait();lease?.release();if(leaseRef.current===lease)leaseRef.current=undefined;if(cleanupBarrierRef.current===barrier)cleanupBarrierRef.current=undefined;if(mountedRef.current&&runId===runIdRef.current&&samplerRef.current===sampler){samplerRef.current=undefined;setRunning(false);onRunningChange(false);retryRef.current=undefined;if(sampler&&guided&&!checkSound&&(runTakeCountRef.current>0||retainedCount>0))onCaptureReview?.();}}};
  const stop=useCallback(async()=>{if(stopOperationRef.current)return stopOperationRef.current;const owned=samplerRef.current;if(!owned)return;const lease=leaseRef.current,barrier=cleanupBarrierRef.current;invalidateCheck();const stopId=++runIdRef.current;const operation=(async()=>{try{await owned.cancel();}finally{await barrier?.wait();lease?.release();if(leaseRef.current===lease)leaseRef.current=undefined;if(cleanupBarrierRef.current===barrier)cleanupBarrierRef.current=undefined;}if(mountedRef.current&&runIdRef.current===stopId&&samplerRef.current===owned){samplerRef.current=undefined;setRunning(false);onRunningChange(false);const hasTakes=runTakeCountRef.current>0||retainedCount>0;setProgress(hasTakes?'Automatic capture stopped. Finished takes remain in review.':'Automatic capture stopped before a take was completed.');if(hasTakes)onCaptureReview?.();}})();stopOperationRef.current=operation;try{await operation;}finally{if(stopOperationRef.current===operation)stopOperationRef.current=undefined;}},[invalidateCheck,onCaptureReview,onRunningChange,retainedCount]);
  useEffect(()=>{const changed=()=>{invalidateCheck();setProgress('');refreshOutputs();if(outputId&&WebMidi.getOutputById(outputId)?.state!=='connected'){void stop();setError('The selected MIDI output disconnected. Reconnect it, then retry. If the instrument is still sounding, stop the note on the instrument.');}};if(WebMidi.enabled)WebMidi.addListener('portschanged',changed);return()=>{if(WebMidi.enabled)WebMidi.removeListener('portschanged',changed);};},[invalidateCheck,midiEnabled,outputId,refreshOutputs,stop]);
  useEffect(()=>{const visibility=()=>{if(document.hidden&&samplerRef.current){void stop();setError('Automatic capture stopped because the page was hidden. Finished takes remain in review.');}};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[stop]);
  const applyProfile=(next:Profile)=>{routesRef.current={...routesRef.current,[profile]:{audioDeviceId:desiredAudioRef.current??audioDeviceId,outputId,settings}};const route=routesRef.current[next];setProfile(next);setOutputId(route.outputId);setSettings(route.settings);desiredAudioRef.current=route.audioDeviceId&&route.audioDeviceId!==audioDeviceId?route.audioDeviceId:null;setInputResolutionRequired(false);if(!route.audioDeviceId)onAudioDeviceChange('');else if(route.audioDeviceId===audioDeviceId||audioDevices.some(device=>device.deviceId===route.audioDeviceId))onAudioDeviceChange(route.audioDeviceId);else{setInputResolutionRequired(true);onAudioDeviceChange('');setError('The saved audio input is unavailable. Choose an input before capture.');}};
  const notes=useMemo(()=>{try{return noteSequence(settings);}catch{return[];}},[settings]);
  const captureSeconds=notes.length*(settings.holdSeconds+settings.tailSeconds+settings.settleSeconds);
  const showConnect=!guided||guidedStep==='connect',showCapture=!guided||guidedStep==='capture',showReview=guided&&guidedStep==='review';
  return <fieldset data-studio-automatic-panel data-initial-focus={props.initialFocus?'true':undefined} tabIndex={-1} hidden={guidedStep==='finish'} disabled={disabled&&!running} className={guided?'studio-guided-panel':undefined} style={{border:'1px solid var(--color-border-medium, #bbb)',borderRadius:6,padding:10,marginTop:12}}><legend>{guided?'Guided automatic multisampling':'Automatic multisampling'}</legend>
    {showConnect&&<section aria-labelledby={guided?'guided-connect-heading':undefined}>
      {guided&&<><h3 id="guided-connect-heading">Connect and check</h3><p>Choose matching audio and MIDI routes. Nothing is enabled until you use the buttons below.</p></>}
      <div className="studio-guided-fields">
        {guided&&<label>Audio input<select aria-label="Guided audio input" value={audioDeviceId} disabled={running} onChange={event=>onExplicitAudioDeviceChange(event.target.value)} style={{...button,width:'100%'}}><option value="">Default input</option>{audioDevices.map(device=><option key={device.deviceId} value={device.deviceId}>{device.label}</option>)}</select></label>}
        <label>Routing example (optional)<select aria-label="Routing profile" value={profile} disabled={running} onChange={event=>applyProfile(event.target.value as Profile)} style={{...button,width:'100%'}}><option value="custom">Custom hardware or software</option><option value="nina-digitakt">Hardware routing example</option><option value="ableton">Software routing example</option></select></label>
        <label>MIDI output<select aria-label="MIDI output" value={outputId} disabled={!midiEnabled||running} onChange={event=>setOutputId(event.target.value)} style={{...button,width:'100%'}}><option value="">Choose output</option>{outputs.map(output=><option key={output.id} value={output.id}>{output.name}</option>)}</select></label>
        <NumberField label="MIDI channel" value={settings.channel} min={1} max={16} step={1} disabled={running} set={value=>setNumber('channel',value)}/><NumberField label="Velocity" value={settings.velocity} min={1} max={127} step={1} disabled={running} set={value=>setNumber('velocity',value)}/>{guided&&<NumberField label="Check note" inputLabel="Start note" value={settings.startNote} min={0} max={127} step={1} disabled={running} set={value=>setNumber('startNote',value)}/>} 
      </div>
      <p>{profileHelp(profile)}</p>
      <details><summary>Connection checklist</summary><ol>{setupSteps[profile].map(step=><li key={step}>{step}</li>)}</ol><p>The check measures the captured return but cannot identify the instrument. There is no microphone monitoring. Audition and confirm it yourself.</p></details>
      <div className="studio-action-row"><button type="button" onClick={()=>void enableMidi()} disabled={running||midiEnabled||previewActive} style={button}>{midiEnabled?'MIDI enabled':'Enable MIDI'}</button><button type="button" onClick={()=>void begin(settings.startNote,false,true)} disabled={running||disabled||previewActive} style={button}>Check sound on one note</button>{guidedStep==='connect'&&<button type="button" onClick={()=>void stop()} disabled={!running} style={button}>Stop sound check</button>}{checkEvidence?.routeKey===routeKey&&<><button type="button" onClick={()=>onAuditionCheck?.(checkEvidence.audioBuffer)} disabled={running||previewActive} style={button}>Audition check note</button><button type="button" onClick={onStopAudition} disabled={!previewActive} style={button}>Stop check preview</button></>}</div>
      {checkEvidence?.routeKey===routeKey&&guided&&<label className="studio-guided-confirm"><input type="checkbox" checked={heardConfirmed} disabled={running} onChange={event=>setHeardConfirmed(event.target.checked)}/> I heard the intended instrument in the check note.</label>}
      {(guided||profile!=='custom')&&<p role="status">{checkReady?'Sound check confirmed for the current settings.':guided?'A fresh sound check and listening confirmation are required before guided capture.':'Sound check is required before range capture for saved routing examples.'}</p>}
      {guided&&<div className="studio-guided-actions"><button type="button" className="studio-button-primary" onClick={()=>onGuidedStepChange?.(retryNotes.length?'review':'capture')} disabled={!checkReady||running||previewActive}>{retryNotes.length?'Return to review retries':'Continue to capture range'}</button></div>}
    </section>}
    {showCapture&&<section aria-labelledby={guided?'guided-capture-heading':undefined}>
      {guided&&<><h3 id="guided-capture-heading">Capture range</h3><p>Choose the span and spacing. Each note waits for real audio frames before its hold begins.</p></>}
      <div className="studio-guided-fields"><NumberField label="Start note" value={settings.startNote} min={0} max={127} step={1} disabled={running} set={value=>setNumber('startNote',value)}/><NumberField label="End note" value={settings.endNote} min={0} max={127} step={1} disabled={running} set={value=>setNumber('endNote',value)}/><NumberField label="Note step" value={settings.step} min={1} max={127} step={1} disabled={running} set={value=>setNumber('step',value)}/><NumberField label="Hold duration" value={settings.holdSeconds} min={0} max={17.9} step={.05} disabled={running} set={value=>setNumber('holdSeconds',value)}/><NumberField label="Release tail" value={settings.tailSeconds} min={0} max={17.9} step={.05} disabled={running} set={value=>setNumber('tailSeconds',value)}/><NumberField label="Between-note settling" value={settings.settleSeconds} min={0} max={5} step={.05} disabled={running} set={value=>setNumber('settleSeconds',value)}/><NumberField label="Audio readiness timeout" value={settings.readinessTimeoutSeconds} min={.1} max={10} step={.1} disabled={running} set={value=>setNumber('readinessTimeoutSeconds',value)}/></div>
      <p>Range: MIDI {settings.startNote} to {settings.endNote}, every {settings.step} semitone{settings.step===1?'':'s'}; {notes.length} note{notes.length===1?'':'s'}, about {captureSeconds.toFixed(1)} seconds plus input readiness.</p>
      {guided&&!checkReady&&<p role="alert">The sound check is no longer valid for these settings. Return to Connect and check again.</p>}
      <div className="studio-action-row">{guided&&<button type="button" onClick={()=>onGuidedStepChange?.('connect')} disabled={running}>Back to Connect and check</button>}<button type="button" onClick={()=>void begin(settings.startNote)} disabled={running||disabled||previewActive||guided&&!checkReady} style={button}>Test one note</button><button type="button" onClick={()=>void begin()} disabled={running||disabled||previewActive||guided&&!checkReady} style={button}>Start automatic capture</button><button type="button" onClick={()=>void stop()} disabled={!running} style={button}>Stop automatic capture</button>{!guided&&retryNotes.map(note=><button key={note} type="button" onClick={()=>void begin(note,true)} disabled={running||disabled||previewActive} style={button}>Retry MIDI note {note}</button>)}</div>
    </section>}
    {showReview&&<section aria-labelledby="guided-retry-heading"><h3 id="guided-retry-heading">Review and retry</h3>{retryNotes.length?<><p>Warned takes remain in review. Retries use the current settings and require a current confirmed sound check.</p><div className="studio-action-row">{retryNotes.map(note=><button key={note} type="button" onClick={()=>void begin(note,true)} disabled={running||disabled||previewActive||!checkReady} style={button}>Retry MIDI note {note} with current settings</button>)}</div>{!checkReady&&<button type="button" onClick={()=>onGuidedStepChange?.('connect')} disabled={running} style={button}>Renew sound check before retry</button>}</>:<p>No warned MIDI notes are waiting for retry.</p>}<div className="studio-guided-actions"><button type="button" onClick={()=>onGuidedStepChange?.('capture')} disabled={running}>Capture more notes</button><button type="button" onClick={()=>void stop()} disabled={!running}>Stop automatic capture</button></div></section>}
    {!guided&&<p>Each MIDI note starts only after real audio frames arrive. Timing follows the browser and interface; it is not sample-accurate.</p>}
    {progress&&<p role="status">{progress}</p>}{error&&<p role="alert">{error}</p>}
  </fieldset>;
}

function NumberField({label,inputLabel=label,value,min,max,step,disabled,set}:{label:string;inputLabel?:string;value:number;min:number;max:number;step:number;disabled:boolean;set:(value:number)=>void}){return <label>{label}<input aria-label={inputLabel} type="number" value={value} min={min} max={max} step={step} disabled={disabled} onChange={event=>set(Number(event.target.value))} style={{...button,width:'100%'}}/></label>;}
